apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.7.1
    helm:
      valuesObject:
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
          reclaimPolicy: Retain
        defaultSettings:
          defaultReplicaCount: 2
          storageMinimalAvailablePercentage: 10
        ingress:
          enabled: true
          ingressClassName: traefik
          host: longhorn.local.domain
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
