apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 32.1.0
    helm:
      valuesObject:
        deployment:
          replicas: 1
        service:
          type: LoadBalancer
          annotations:
            metallb.universe.tf/loadBalancerIPs: 10.30.0.100
        ports:
          web:
            port: 80
          websecure:
            port: 443
            tls:
              enabled: true
        ingressRoute:
          dashboard:
            enabled: true
            entryPoints: ["websecure"]
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
