---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers
  namespace: traefik
spec:
  headers:
    browserXssFilter: true
    contentTypeNosniff: true
    forceSTSHeader: true
    stsIncludeSubdomains: true
    stsPreload: true
    stsSeconds: 31536000
    customFrameOptionsValue: "SAMEORIGIN"
    customResponseHeaders:
      X-Forwarded-Proto: "https"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit
  namespace: traefik
spec:
  rateLimit:
    average: 100
    burst: 50
    period: 1m

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: internal-only
  namespace: traefik
spec:
  ipWhiteList:
    sourceRange:
      - 10.30.0.0/24
      - 172.10.0.0/24
      - 127.0.0.1/32

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: compress
  namespace: traefik
spec:
  compress: {}

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: external-chain
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: security-headers
      - name: rate-limit
      - name: compress

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: internal-chain
  namespace: traefik
spec:
  chain:
    middlewares:
      - name: internal-only
      - name: security-headers
      - name: compress
