---
apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  defaultCertificate:
    secretName: shreck-io-tls
  
  defaultGeneratedCert:
    resolver: letsencrypt-prod
    domain:
      main: shreck.io
      sans:
        - "*.shreck.io"
        - "*.home.shreck.io"
