apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://cloudflare.github.io/helm-charts
    chart: cloudflare-tunnel-remote
    targetRevision: 0.3.0
    helm:
      valuesObject:
        replicaCount: 2
        
        image:
          repository: cloudflare/cloudflared
          tag: latest
        
        cloudflare:
          tunnelToken: ""  # Will be provided by secret
        
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
