# Staging issuer for testing (won't hit rate limits)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: charlieshreck@gmail.com
    
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    
    solvers:
      - dns01:
          cloudflare:
            email: charlieshreck@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: CLOUDFLARE_API_TOKEN
        selector:
          dnsZones:
            - shreck.io

---
# Production issuer (use after testing with staging)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: charlieshreck@gmail.com
    
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    
    solvers:
      - dns01:
          cloudflare:
            email: charlieshreck@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: CLOUDFLARE_API_TOKEN
        selector:
          dnsZones:
            - shreck.io