---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: cloudflare-api-token-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        api-token: "{{ .apiToken }}"
  
  data:
    - secretKey: apiToken
      remoteRef:
        key: kubernetes/cloudflare
        property: api_token
