---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  hostAPI: https://app.infisical.com/api
  
  authentication:
    serviceToken:
      secretsScope:
        secretsPath: "/kubernetes"
        envSlug: "prod"
      serviceTokenSecretReference:
        secretName: infisical-service-token
        secretNamespace: infisical-operator-system
  
  managedSecretReference:
    secretName: cloudflare-api-token-secret
    secretType: Opaque
    creationPolicy: Owner
