# This resource tells the Infisical Operator how to sync your Cloudflare API token.
# It uses the 'universalAuth' method, which is confirmed to be working.
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  hostAPI: https://app.infisical.com/api
  
  authentication:
    universalAuth:
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: "infisical-operator-system"
      secretsScope:
        projectSlug: "homelab-test-5-ig-k" # Using the slug you provided
        envSlug: "prod"
        secretsPath: "/kubernetes"
        
  managedSecretReference:
    secretName: cloudflare-api-token-secret
    secretNamespace: cert-manager
    secretType: Opaque
    creationPolicy: Owner
