---
# Production certificate for Traefik namespace only
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-shreck-io
  namespace: traefik
spec:
  secretName: shreck-io-tls
  
  duration: 2160h  # 90 days
  renewBefore: 360h # 15 days before expiry
  
  commonName: shreck.io
  
  dnsNames:
    - shreck.io
    - "*.shreck.io"
  
  issuerRef:
    name: letsencrypt-prod  # Change to staging for testing
    kind: ClusterIssuer
    group: cert-manager.io
  
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  
  usages:
    - digital signature
    - key encipherment