---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
# Staging certificate for testing
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-shreck-io-staging
  namespace: traefik
spec:
  secretName: shreck-io-tls
  
  duration: 2160h  # 90 days
  renewBefore: 360h # 15 days before expiry
  
  commonName: shreck.io
  
  dnsNames:
    - shreck.io
    - "*.shreck.io"
  
  issuerRef:
    name: letsencrypt-staging  # ← Using staging
    kind: ClusterIssuer
    group: cert-manager.io
  
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  
  usages:
    - digital signature
    - key encipherment

---
# Duplicate for argocd namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-shreck-io-staging
  namespace: argocd
spec:
  secretName: shreck-io-tls
  duration: 2160h
  renewBefore: 360h
  commonName: shreck.io
  dnsNames:
    - shreck.io
    - "*.shreck.io"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io

---
# Duplicate for longhorn-system namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-shreck-io-staging
  namespace: longhorn-system
spec:
  secretName: shreck-io-tls
  duration: 2160h
  renewBefore: 360h
  commonName: shreck.io
  dnsNames:
    - shreck.io
    - "*.shreck.io"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io

---
# Duplicate for media namespace
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-shreck-io-staging
  namespace: media
spec:
  secretName: shreck-io-tls
  duration: 2160h
  renewBefore: 360h
  commonName: shreck.io
  dnsNames:
    - shreck.io
    - "*.shreck.io"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io