apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: linuxserver/plex:latest
        ports:
        - name: plex
          containerPort: 32400
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/London"
        - name: VERSION
          value: "docker"
        - name: PLEX_CLAIM
          valueFrom:
            secretKeyRef:
              name: plex-secrets
              key: PLEX_CLAIM
        volumeMounts:
        - name: config
          mountPath: /config
        - name: transcode
          mountPath: /transcode
        - name: media
          mountPath: /tv
          subPath: tv
        - name: media
          mountPath: /movies
          subPath: film
        - name: media
          mountPath: /downloads
          subPath: downloads
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 2000m
            memory: 2Gi
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: plex-config
      - name: transcode
        emptyDir: {}
      - name: media
        nfs:
          server: 10.30.0.120
          path: /mnt/Truro/k8s
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: media
spec:
  type: LoadBalancer
  loadBalancerIP: 10.30.0.95
  ports:
  - name: plex
    port: 32400
    targetPort: 32400
  selector:
    app: plex
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi