# ==============================================================================
# Longhorn Values - Ultra-Low Memory Configuration for 8GB Workers
# ==============================================================================

# ==============================================================================
# Service Configuration
# ==============================================================================
service:
  ui:
    type: LoadBalancer
    loadBalancerIP: "10.30.0.70"

# ==============================================================================
# Resource Limits - AGGRESSIVE reduction for OOM prevention
# ==============================================================================

# Longhorn Manager (runs on every node)
longhornManager:
  resources:
    requests:
      cpu: 100m
      memory: 96Mi
    limits:
      cpu: 500m
      memory: 384Mi

# Longhorn Driver (CSI driver)
longhornDriver:
  resources:
    requests:
      cpu: 50m
      memory: 48Mi
    limits:
      cpu: 200m
      memory: 192Mi

# Longhorn UI
longhornUI:
  resources:
    requests:
      cpu: 50m
      memory: 48Mi
    limits:
      cpu: 200m
      memory: 192Mi

# Instance Manager (biggest memory consumer)
instanceManager:
  resources:
    requests:
      cpu: 100m
      memory: 96Mi
    limits:
      cpu: 500m
      memory: 384Mi

# ==============================================================================
# CSI Components - Minimal allocation
# ==============================================================================
csi:
  attacher:
    resources:
      requests:
        cpu: 50m
        memory: 48Mi
      limits:
        cpu: 200m
        memory: 192Mi
  
  provisioner:
    resources:
      requests:
        cpu: 50m
        memory: 48Mi
      limits:
        cpu: 200m
        memory: 192Mi
  
  resizer:
    resources:
      requests:
        cpu: 50m
        memory: 48Mi
      limits:
        cpu: 200m
        memory: 192Mi
  
  snapshotter:
    resources:
      requests:
        cpu: 50m
        memory: 48Mi
      limits:
        cpu: 200m
        memory: 192Mi
  
  nodeDriverRegistrar:
    resources:
      requests:
        cpu: 50m
        memory: 48Mi
      limits:
        cpu: 200m
        memory: 192Mi

# ==============================================================================
# Longhorn Settings
# ==============================================================================
defaultSettings:
  defaultDataPath: "/var/lib/longhorn"
  defaultReplicaCount: "2"
  storageMinimalAvailablePercentage: "10"
  concurrentReplicaRebuildPerNodeLimit: "1"
  autoSalvage: "false"
  replicaReplenishmentWaitInterval: "300"
  autoDeletePodWhenVolumeDetachedUnexpectedly: "false"

# ==============================================================================
# Persistence Settings
# ==============================================================================
persistence:
  defaultClass: true
  defaultClassReplicaCount: 2
  reclaimPolicy: Delete

# ==============================================================================
# Pre-Upgrade Checker
# ==============================================================================
preUpgradeChecker:
  jobEnabled: false

# ==============================================================================
# Additional Stability Settings
# ==============================================================================
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

priorityClass:
  create: true
  name: longhorn-critical
  value: 1000000

# ==============================================================================
# NOTES
# ==============================================================================
# Memory Budget per Worker (8GB total):
# - System:             ~800Mi
# - Cilium:             ~200Mi
# - Longhorn (total):   ~432Mi  (REDUCED from 576Mi)
#   - Manager:          96Mi
#   - Instance Mgr:     96Mi
#   - CSI components:   240Mi
# - Apps (Sonarr/etc):  ~768Mi
# - Available:          ~5.8GB for workloads
# ==============================================================================