# ==============================================================================
# Longhorn Values - Resource-Limited Configuration
# ==============================================================================
# This configuration prevents worker node OOM crashes by limiting resource usage
# during Longhorn installation and operation.
# ==============================================================================

# ==============================================================================
# Service Configuration
# ==============================================================================
service:
  ui:
    type: LoadBalancer
    loadBalancerIP: "10.30.0.70"

# ==============================================================================
# Resource Limits - CRITICAL for 8GB workers
# ==============================================================================
# These limits prevent OOM crashes during installation surges

# Longhorn Manager (runs on every node)
longhornManager:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi      # Reduced from default 256Mi
    limits:
      cpu: 500m
      memory: 512Mi      # Prevents runaway memory usage

# Longhorn Driver (CSI driver)
longhornDriver:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Longhorn UI
longhornUI:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Instance Manager (biggest memory consumer)
instanceManager:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi      # Reduced from default 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# ==============================================================================
# CSI Components - All reduced to prevent surge
# ==============================================================================
csi:
  # CSI Attacher
  attacher:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  
  # CSI Provisioner
  provisioner:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  
  # CSI Resizer
  resizer:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  
  # CSI Snapshotter
  snapshotter:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  
  # CSI Node Driver Registrar
  nodeDriverRegistrar:
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi

# ==============================================================================
# Longhorn Settings
# ==============================================================================
defaultSettings:
  # Storage path on each node
  defaultDataPath: "/var/lib/longhorn"
  
  # Number of replicas per volume
  defaultReplicaCount: "2"
  
  # Minimum available storage percentage before warning
  storageMinimalAvailablePercentage: "10"
  
  # CRITICAL: Limit concurrent rebuilds to prevent resource spikes
  concurrentReplicaRebuildPerNodeLimit: "1"
  
  # Disable automatic salvage to prevent cascading failures
  autoSalvage: "false"
  
  # Increase timeout to prevent premature failures during high load
  replicaReplenishmentWaitInterval: "300"
  
  # Disable automatic deletion of failed replicas
  # (Gives you time to investigate before cleanup)
  autoDeletePodWhenVolumeDetachedUnexpectedly: "false"

# ==============================================================================
# Persistence Settings
# ==============================================================================
persistence:
  # Make Longhorn the default StorageClass
  defaultClass: true
  
  # Default number of replicas for new volumes
  defaultClassReplicaCount: 2
  
  # Reclaim policy: Delete volumes when PVC is deleted
  reclaimPolicy: Delete

# ==============================================================================
# Pre-Upgrade Checker - Disabled to prevent issues
# ==============================================================================
preUpgradeChecker:
  jobEnabled: false

# ==============================================================================
# Additional Stability Settings
# ==============================================================================

# Tolerations - allow Longhorn to run on all nodes
tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

# Priority class - ensure Longhorn stays running
priorityClass:
  create: true
  name: longhorn-critical
  value: 1000000

# ==============================================================================
# NOTES
# ==============================================================================
# Memory Budget per Worker (8GB total):
# - System:             ~800Mi
# - Cilium:             ~200Mi
# - Longhorn (total):   ~576Mi
#   - Manager:          128Mi
#   - Instance Mgr:     128Mi
#   - CSI components:   320Mi
# - Apps (Sonarr/etc):  ~768Mi
# - Available:          ~5.6GB for workloads
#
# This configuration ensures stable operation without OOM crashes.
# ==============================================================================