# ==============================================================================
# Longhorn Values - Single Worker Test Configuration (Manageable)
# ==============================================================================

service:
  ui:
    type: LoadBalancer
    loadBalancerIP: "10.30.0.70"

longhornManager:
  resources:
    requests:
      cpu: 100m
      memory: 96Mi
    limits:
      cpu: 500m
      memory: 384Mi

longhornDriver:
  resources:
    requests:
      cpu: 50m
      memory: 48Mi
    limits:
      cpu: 200m
      memory: 192Mi

longhornUI:
  resources:
    requests:
      cpu: 50m
      memory: 48Mi
    limits:
      cpu: 200m
      memory: 192Mi

instanceManager:
  resources:
    requests:
      cpu: 100m
      memory: 96Mi
    limits:
      cpu: 500m
      memory: 384Mi

csi:
  attacher:
    resources:
      requests:
        cpu: 50m
        memory: 48Mi
      limits:
        cpu: 200m
        memory: 192Mi
  
  provisioner:
    resources:
      requests:
        cpu: 50m
        memory: 48Mi
      limits:
        cpu: 200m
        memory: 192Mi
  
  resizer:
    resources:
      requests:
        cpu: 50m
        memory: 48Mi
      limits:
        cpu: 200m
        memory: 192Mi
  
  snapshotter:
    resources:
      requests:
        cpu: 50m
        memory: 48Mi
      limits:
        cpu: 200m
        memory: 192Mi
  
  nodeDriverRegistrar:
    resources:
      requests:
        cpu: 50m
        memory: 48Mi
      limits:
        cpu: 200m
        memory: 192Mi

defaultSettings:
  defaultDataPath: "/var/lib/longhorn"
  defaultReplicaCount: "1"
  storageMinimalAvailablePercentage: "15"
  concurrentReplicaRebuildPerNodeLimit: "1"
  autoSalvage: "true"
  replicaReplenishmentWaitInterval: "300"
  autoDeletePodWhenVolumeDetachedUnexpectedly: "true"

persistence:
  defaultClass: true
  defaultClassReplicaCount: 1
  reclaimPolicy: Delete

preUpgradeChecker:
  jobEnabled: false

priorityClass:
  create: true
  name: longhorn-critical
  value: 1000000