kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: multus
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
rules:
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ['*']
    verbs: ['*']
  - apiGroups: [""]
    resources: ["pods", "pods/status"]
    verbs: ["get", "update", "list", "watch"]
  - apiGroups: ["", "events.k8s.io"]
    resources: ["events"]
    verbs: ["create", "patch", "update"]