apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: install-cni-plugins
  namespace: kube-system
  labels:
    app: cni-plugins-installer
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    matchLabels:
      name: cni-plugins-installer
  template:
    metadata:
      labels:
        name: cni-plugins-installer
    spec:
      hostNetwork: true
      tolerations:
        - operator: Exists
      initContainers:
        - name: install-cni-plugins
          image: rancher/mirrored-flannelcni-flannel-cni-plugin:v1.2.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "Installing CNI plugins..."
              cp -f /opt/cni/bin/* /host/opt/cni/bin/ || true
              echo "Done"
          volumeMounts:
            - name: cni-bin
              mountPath: /host/opt/cni/bin
          securityContext:
            privileged: true
      containers:
        - name: pause
          image: gcr.io/google_containers/pause:3.2
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin
