apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: install-cni-plugins
  namespace: kube-system
  labels:
    app: cni-plugins-installer
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    matchLabels:
      name: cni-plugins-installer
  template:
    metadata:
      labels:
        name: cni-plugins-installer
    spec:
      hostNetwork: true
      tolerations:
        - operator: Exists
      initContainers:
        - name: install-cni-plugins
          image: ghcr.io/containernetworking/plugins:v1.5.1
          command: ["/bin/sh"]
          args:
            - -c
            - |
              set -e
              echo "Installing CNI plugins..."
              cp /opt/cni/bin/* /host/opt/cni/bin/
              echo "CNI plugins installed"
              ls -la /host/opt/cni/bin/
          volumeMounts:
            - name: cni-bin
              mountPath: /host/opt/cni/bin
          securityContext:
            privileged: true
      containers:
        - name: pause
          image: ghcr.io/containernetworking/plugins:v1.5.1
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 10m
              memory: 16Mi
      volumes:
        - name: cni-bin
          hostPath:
            path: /opt/cni/bin