---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflared
data:
  config.yaml: |
    tunnel: d09156ee-ce83-45ac-9837-35646b34b80f
    credentials-file: /etc/cloudflared/creds/credentials.json
    
    ingress:
      - hostname: argocd.shreck.io
        service: https://traefik-traefik.traefik.svc.cluster.local:443
        originRequest:
          originServerName: shreck.io
          noTLSVerify: false
      
      - hostname: longhorn.shreck.io
        service: https://traefik-traefik.traefik.svc.cluster.local:443
        originRequest:
          originServerName: shreck.io
          noTLSVerify: false
      
      - hostname: "*.shreck.io"
        service: https://traefik-traefik.traefik.svc.cluster.local:443
        originRequest:
          originServerName: shreck.io
          noTLSVerify: false
      
      - service: http_status:404

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
  namespace: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 128Mi
      volumes:
      - name: config
        configMap:
          name: cloudflared-config
      - name: creds
        secret:
          secretName: cloudflared-tunnel-credentials
          items:
          - key: TUNNEL_TOKEN
            path: credentials.json