---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared
spec:
  hostAPI: https://app.infisical.com/api
  
  authentication:
    universalAuth:
      credentialsRef:
        secretName: "universal-auth-credentials"
        secretNamespace: "infisical-operator-system"
      secretsScope:
        projectSlug: "homelab-test-5-ig-k"
        envSlug: "prod"
        secretsPath: "/kubernetes"
        
  managedSecretReference:
    secretName: cloudflared-tunnel-credentials
    secretNamespace: cloudflared
    secretType: Opaque
    creationPolicy: Owner