output "talos_config" {
  value     = data.talos_client_configuration.this.talos_config
  sensitive = true
}

output "kubeconfig" {
  value     = talos_cluster_kubeconfig.this.kubeconfig_raw
  sensitive = true
  description = "Note: Use the file at generated/kubeconfig instead - it's generated by talosctl with correct certificates"
}

output "kubeconfig_path" {
  value       = "${path.module}/generated/kubeconfig"
  description = "Path to the working kubeconfig file (generated by talosctl)"
}

output "control_plane_ip" {
  description = "Control plane IP address"
  value       = var.control_plane.ip
}

output "worker_ips" {
  description = "Worker node IP addresses"
  value       = [for w in var.workers : w.ip]
}

output "cluster_info" {
  description = "Cluster information"
  value = {
    control_plane_ip = var.control_plane.ip
    worker_ips       = [for w in var.workers : w.ip]
    vm_ids = {
      control_plane = local.vm_ids.control_plane
      workers       = local.vm_ids.workers
    }
    storage_pools = {
      vms      = var.proxmox_storage
      mayastor = var.proxmox_mayastor_storage
    }
    versions = {
      talos      = var.talos_version
      kubernetes = var.kubernetes_version
    }
    cilium_lb_ip_pool = var.cilium_lb_ip_pool
    kubeconfig_path  = "${path.module}/generated/kubeconfig"
    talosconfig_path = "${path.module}/generated/talosconfig"
  }
}