apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: 32.1.0
    helm:
      valuesObject:
        deployment:
          replicas: 2
        
        service:
          enabled: true
          type: LoadBalancer
          annotations:
            metallb.universe.tf/loadBalancerIPs: "10.30.0.100"
        
        ports:
          web:
            port: 80
            redirectTo:
              port: websecure
              priority: 10
          
          websecure:
            port: 443
            tls:
              enabled: true
            http3:
              enabled: true
        
        providers:
          kubernetesCRD:
            enabled: true
            allowCrossNamespace: true
          kubernetesIngress:
            enabled: true
        
        logs:
          general:
            level: INFO
          access:
            enabled: true
            format: json
        
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
