apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.10.0
    helm:
      # Skip hooks if causing issues
      skipCrds: false
      valuesObject:
        service:
          ui:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/loadBalancerIPs: "10.30.0.70"
        
        defaultSettings:
          defaultDataPath: "/var/lib/longhorn"
          defaultReplicaCount: "2"
          storageMinimalAvailablePercentage: "10"
        
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
        
        # Important: Create ServiceAccount first
        preUpgradeChecker:
          jobEnabled: true
  
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    # Add retry logic for timing issues
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m