apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  sources:
    # Helm chart
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.10.0
      helm:
        valueFiles:
          - $values/kubernetes/platform/longhorn/resources/values.yaml
    
    # Git repo with values
    - repoURL: https://github.com/charlieshreck/homelab-test.git
      targetRevision: main
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  
  # Ignore the pre-upgrade job if it exists
  ignoreDifferences:
    - group: batch
      kind: Job
      name: longhorn-pre-upgrade
      jsonPointers:
        - /status