apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.10.0
    helm:
      valuesObject:
        service:
          ui:
            type: LoadBalancer
            annotations:
              metallb.universe.tf/loadBalancerIPs: "10.30.0.70"
        
        defaultSettings:
          defaultDataPath: "/var/lib/longhorn"
          defaultReplicaCount: "2"
          storageMinimalAvailablePercentage: "10"
          # Remove storageNetwork setting
        
        persistence:
          defaultClass: true
          defaultClassReplicaCount: 2
  
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true