apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-csi-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/charlieshreck/homelab-test.git
    targetRevision: main
    path: kubernetes/platform/nfs-csi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true