---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    # Required for Longhorn - allows privileged pods
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged